export const products = [
  {
    id: 1,
    name: "Kacamata casual hitam",
    category: "Kacamata",
    price: 15,
    image: "/images/product1.jpg",
    isCart: false,
    description: "Kacamata Fashion dengan desain yang modern dan gaya yang stylish.",
  },
  {
    id: 2,
    name: "Hyejin Dress",
    category: "Dress",
    price: 25,
    image: "/images/product2.jpg",
    isCart: false,
    description: "Dress casual dengan potongan lengan panjang dan desain yang trendi.",
  },
  {
    id: 3,
    name: "Sepatu sneakers Piero Rusher Lux",
    category: "Sepatu",
    price: 35,
    image: "/images/product3.jpg",
    isCart: false,
    description: "Sepatu sneakers dengan gaya streetwear yang trendy.",
  },
  {
    id: 4,
    name: "Long Cargo Pants",
    category: "Celana",
    price: 40,
    image: "/images/product4.jpg",
    isCart: false,
    description: "Celana panjang pria dengan  Ciri khas dari celana ini adalah adanya katong berukuran besar pada bagian kanan dan kiri sisinya.",
  },
  {
    id: 5,
    name: "Midi Dress Korea",
    category: "Dress",
    price: 25,
    image: "/images/product5.jpg",
    isCart: false,
    description: "dress yang memiliki panjang rok sampai lutut atau sedikit ke bawah dan memiliki model yang simpel dan feminin.",
  },
  {
    id: 6,
    name: "Kacamata Photocromic",
    category: "Kacamata",
    price: 18,
    image: "/images/product6.jpg",
    isCart: false,
    description: " kacamata photochromic adalah salah satu jenis lensa kacamata yang warnanya bisa bertransisi menjadi lebih gelap ketika terpapar oleh sinar matahari atau sinar UV lainnya.",
  },
  {
    id: 7,
    name: "Sepatu Ventela Konnijiwa",
    category: "Sepatu",
    price: 18,
    image: "/images/product7.jpg",
    isCart: false,
    description: "Sepatu kolaborasi ventela x jeromepolin dengan nama Konnijiwa.Insole terbuat dari Ultralite Foam menjadikan Ventela sangat empuk dan nyaman dipakai dan pada strip bisa menyala pada kegelapan",
  },
  {
    id: 8,
    name: "Wide Kulot Pants Cigarette",
    category: "Celana",
    price: 50,
    image: "/images/product8.jpg",
    isCart: false,
    description: "kulot Polos Korea Tinggi Katun Cigaret yang nyaman di gunakan saat beraktivitas.",
  },
];
